repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
    - id: isort
      language: python
      types: [python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      language: python
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint gg_project
      language: system
      always_run: true
      pass_filenames: false
